version: '3.1'


services:
  api-gateway:
    build:
      context: Dockerfile
    container_name: petrovedge-api-gateway
    image: go-app-win:latest
    ports:
      - 80:85
    restart: always
    networks:
      - api
  ethereum-client:
    image: ethereum/client-go
    ports:
      - 30303:30303
  besu:
    image: hyperledger/besu:latest 
    ports: 
      - 8545:8545